// Generated by CoffeeScript 1.9.2
(function() {
  (function($) {
    return $(function() {
      var db, insert;
      db = new PouchDB('db');
      insert = function(post) {
        return $('#posts').append(post.content + "<br>");
      };
      $('#add-post-button').click(function() {
        return db.put({
          content: $('#new-post').val(),
          _id: 'post-' + Date.now()
        }).then(function(result) {
          return console.log(result);
        });
      });
      return db.allDocs({
        include_docs: true,
        startkey: 'post-'
      }).then(function(result) {
        var i, len, post, ref, results;
        console.log(result);
        ref = result.rows;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          post = ref[i];
          results.push(insert(post.doc));
        }
        return results;
      });
    });
  })(jQuery);

}).call(this);
