// Generated by CoffeeScript 1.9.2
(function() {
  (function($) {
    return $(function() {
      var from_db, peer1, peer2, to_db;
      peer1 = new window.SimplePeer({
        initiator: true
      });
      peer2 = new window.SimplePeer;
      peer1.on('signal', function(data) {
        return peer2.signal(data);
      });
      peer2.on('signal', function(data) {
        return peer1.signal(data);
      });
      peer2.on('data', function(data) {
        return console.log('got a message from peer1: ' + data);
      });
      from_db = new PouchDB('db');
      to_db = new PouchDB('db_cpy');
      from_db.dump(peer1).then(function(res) {
        console.log(res);
        return console.log("should be 'ok'");
      });
      return to_db.load(peer2).then(function(res) {
        console.log(res);
        return console.log("should be 'ok'");
      });
    });
  })(jQuery);

}).call(this);
